program: train_clip_decoder.py
project: aaai27_encoder_mgpcgrl_fullshot_2_nodec
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['dgpk', 'skzd', 'pkdm']
  overwrite:
    value: false
  decoder_nograd:
    value: true
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fullshot_2_nodec'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
# total runs: 10
