program: train_clip.py
project: aaai27_encoder_vipcgrl_fewshot
method: grid
metric:
  goal: minimize
  name: total/val_loss
parameters:
  game:
    values: ['all']
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/vipcgrl_fewshot'
  unseen_ratio:
    value: 0.03
  unseen_games:
    values:
      - 'pk'
      - 'dg'
      - 'zd'
      - 'dm'
      - 'sk'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
