program: train_mgpcgrl.py
project: aaai27_train_mgpcgrl_fullshot_nodec
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0, 1, 2, 3, 4]
  n_envs:
    value: 600
  overwrite:
    value: false
  encoder.ckpt_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fullshot_nodec'
  encoder.ckpt_name:
    values: [
      "clipdec-game-all_exp-def_dw-0p03_0_nograd",
    ]
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fullshot_nodec'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
# total runs: 1 combo x 5 dataset_reward_enum x 5 seeds = 25
