program: train_clip_decoder.py
project: aaai27_encoder_mgpcgrl_fewshot_unseenrate
method: grid
metric:
  goal: minimize
  name: val/loss
parameters:
  game:
    value: 'all'
  overwrite:
    value: true
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fewshot_unseenrate'
  seen_ratio:
    value: 0.1
  unseen_ratio:
    values: [0.0, 0.001, 0.003, 0.01, 0.03, 0.1, 0.3]
  unseen_games:
    value: 'zd'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
