"""
train_pretrained_clip.py
========================
Pretrained CLIP based PCGRL training.

Use the change in cosine similarity between the map image and text instruction
(instruct_sample.embedding) as the reward.

Usage:
    python -m train_pretrained_clip [overrides]
    python -m train_pretrained_clip dataset_game=dungeon dataset_reward_enum=1
"""
import jax
import jax.numpy as jnp
import hydra

from conf.config import PretrainedCLIPPCGRLConfig
from instruct_rl.utils.log_utils import suppress_jax_debug_logs
from instruct_rl.utils.train_utils import _cosine_similarity, main_entry
from instruct_rl.utils.img_preprocess import render_level_from_arr, clip_batch_preprocess

suppress_jax_debug_logs()


# ── Observation injection: precomputed CLIP text embedding -> nlp_obs ────────

def inject_pretrained_clip_pcgrl_obs(last_obs, env_state, instruct_sample, config, env):
    """Inject text embeddings precomputed by pretrained CLIP into nlp_obs."""
    return last_obs.replace(nlp_obs=instruct_sample.embedding)


# ── Reward injection: map-image/text-embedding cosine-similarity delta ────────

def inject_pretrained_clip_reward(
    prev_env_state,
    curr_env_state,
    instruct_sample,
    network_apply_fn,
    params,
    last_obs,
) -> jnp.ndarray:
    """Pretrained-CLIP cosine-similarity delta reward.

    Render map images, apply CLIP preprocessing, compute state embeddings with
    the vision encoder, and return the cosine-similarity delta against text embeddings.

    Parameters
    ----------
    prev_env_state : LogWrapper state from the previous step
    curr_env_state : LogWrapper state from the current step
    instruct_sample : Instruct
        ``instruct_sample.embedding`` -- precomputed CLIP text embeddings (B, D).
    network_apply_fn : Callable
        ``network.apply`` — CLIP network of  apply function.
    params : PyTree
        network parameter (train_state.params).
    last_obs : Observation
        Current observation, used to replace the pixel_values slot temporarily.

    Returns
    -------
    reward : jnp.ndarray (B,)
        cos_sim(text, curr_map) - cos_sim(text, prev_map)
        Positive reward as the state approaches the text instruction.
    """
    # ── Rendering: env_map -> tile-cell image ─────────────────────────────────
    curr_rendered = jax.vmap(render_level_from_arr)(
        curr_env_state.env_state.env_map
    )  # (B, H_px, W_px, C)
    prev_rendered = jax.vmap(render_level_from_arr)(
        prev_env_state.env_state.env_map
    )

    # ── CLIP preprocessing: float32, resize to 224x224, and normalize ─────────
    curr_clip_pixels = clip_batch_preprocess(curr_rendered.astype(jnp.float32))
    prev_clip_pixels = clip_batch_preprocess(prev_rendered.astype(jnp.float32))

    # ── Obtain state embeddings from the pretrained CLIP vision encoder ──────
    _, _, _, _, curr_state_embed = network_apply_fn(
        params,
        last_obs.replace(pixel_values=curr_clip_pixels),
        return_text_embed=False,
        return_state_embed=True,
    )
    _, _, _, _, prev_state_embed = network_apply_fn(
        params,
        last_obs.replace(pixel_values=prev_clip_pixels),
        return_text_embed=False,
        return_state_embed=True,
    )

    # ── Cosine-similarity delta reward ────────────────────────────────────────
    # Precomputed text embeddings (B, D), generated by the CSV loader before training
    text_embed = instruct_sample.embedding  # already L2-normalized

    curr_sim = _cosine_similarity(text_embed, curr_state_embed)  # (B,)
    prev_sim = _cosine_similarity(text_embed, prev_state_embed)  # (B,)

    # Reward the increase in similarity
    return curr_sim - prev_sim


# ── Hydra entrypoint ──────────────────────────────────────────────────────────

@hydra.main(version_base=None, config_path="./conf", config_name="pretrained_clip_pcgrl")
def main(config: PretrainedCLIPPCGRLConfig):
    main_entry(
        config,
        inject_obs_fn=inject_pretrained_clip_pcgrl_obs,
        inject_reward_fn=inject_pretrained_clip_reward,
    )


if __name__ == "__main__":
    main()

