program: train_ipcgrl_encoder_mg.py
project: aaai27_encoder_ipcgrl_fullshot
method: grid
metric:
  goal: minimize
  name: val/mse_unseen_overall
parameters:
  game:
    values: ['all']
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/ipcgrl_fullshot'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
# total runs: 1
