program: train_clip_decoder.py
project: aaai27_encoder_reward_fullshot_2
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['dgpk', 'skzd', 'pkdm']
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/reward_fullshot_2'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
# total runs: 10
