name: cpcgrl-re5
pod:
  template_id: runpod-torch-v280
  gpu: NVIDIA GeForce RTX 5090
  gpu_count: 1
  network_volume_id: dx18rniw3p
  spot: false
options:
  timeout: true
  time_limit: 43200
  terminate: true
runtime:
  cmds:
  - source /workspace/venv/bin/activate
  - cd /workspace/multigame-pcgrl
  - python train_cpcgrl.py n_envs=600 dataset_reward_enum=5

