program: train_ipcgrl.py
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0]
  n_envs:
    value: 600
  overwrite:
    value: false

  # ipcgrl encoder trained with train_ipcgrl_encoder_unseen.yaml
  encoder.ckpt_dir:
    value: '/mnt/nas/mgpcgrl/ipcgrl_zeroshot'
  encoder.ckpt_name:
    values: [
      # 1 unseen game
#      "ipcgrl-enc-mg-game-all_unseen-pk_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-dg_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-zd_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-dm_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-sk_ur-0.0_enc-mlp_exp-def_0",
      # 2 unseen games
#      "ipcgrl-enc-mg-game-all_unseen-pkdg_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkzd_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkdm_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pksk_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-dgzd_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-dgdm_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-dgsk_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-zddm_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-zdsk_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-dmsk_ur-0.0_enc-mlp_exp-def_0",
      # 3 unseen games
#      "ipcgrl-enc-mg-game-all_unseen-pkdgzd_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkdgdm_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkdgsk_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-pkzddm_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkzdsk_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkdmsk_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-dgzddm_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-dgzdsk_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-dgdmsk_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-zddmsk_ur-0.0_enc-mlp_exp-def_0",
      # 4 unseen games
      "ipcgrl-enc-mg-game-all_unseen-pkdgzddm_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkdgzdsk_ur-0.0_enc-mlp_exp-def_0",
#      "ipcgrl-enc-mg-game-all_unseen-pkdgdmsk_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-pkzddmsk_ur-0.0_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-all_unseen-dgzddmsk_ur-0.0_enc-mlp_exp-def_0",
    ]
  saves_dir:
    value: '/mnt/nas/mgpcgrl/ipcgrl_zeroshot'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}

