defaults:
  - train_finetuned_clip_encoder_schema
  - _self_

hydra:
  sweeper:
    params: {}

# text text text
encoder:
  model: clip
  state: true
  token_max_len: 77

# default data text
game: all