defaults:
  - train_finetuned_clip_encoder_schema
  - _self_

hydra:
  sweeper:
    params: {}

# Training hyperparameters
encoder:
  model: clip
  state: true
  token_max_len: 77

# Default dataset settings
game: all