program: train_clip_decoder.py
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  n_envs:
    value: 600
  overwrite:
    value: false
  instruction_prefix:
    value: 'desc'
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_encoder_unseen_desc'
  unseen_games:
    values:
      # 1 unseen game
#      - 'pk'
#      - 'dg'
      - 'zd'
      - 'dm'
      - 'sk'
      # 2 unseen games
#      - 'pkdg'
#      - 'pkzd'
#      - 'pkdm'
#      - 'pksk'
#      - 'dgzd'
#      - 'dgdm'
#      - 'dgsk'
      - 'zddm'
      - 'zdsk'
      - 'dmsk'
      # 3 unseen games
#      - 'pkdgzd'
#      - 'pkdgdm'
#      - 'pkdgsk'
      - 'pkzddm'
#      - 'pkzdsk'
#      - 'pkdmsk'
      - 'dgzddm'
#      - 'dgzdsk'
#      - 'dgdmsk'
      - 'zddmsk'
      # 4 unseen games
      - 'pkdgzddm'
#      - 'pkdgzdsk'
#      - 'pkdgdmsk'
      - 'pkzddmsk'
      - 'dgzddmsk'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
