program: train_cpcgrl.py
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0, 1, 2, 3, 4]
  n_envs:
    value: 600
  overwrite:
    value: true
  saves_dir:
    value: '/mnt/nas/mgpcgrl/cpcgrl'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  - "overwrite=true"