program: train_mipcgrl_encoder_mg.py
project: aaai27_encoder_mipcgrl_fullshot_3
method: grid
metric:
  goal: minimize
  name: val/mse_unseen_overall
parameters:
  game:
    values: ['dgpksk', 'pkdmzd', 'skdmzd']
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mipcgrl_fullshot_3'
  # ── MIPCGRL  before  for : task classifier weight ──
  classifier_weight:
    value: 1.0
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
# total runs: 10
