program: train_clip_decoder.py
project: aaai27_encoder_mgpcgrl_fullshot_3_dw0
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['dgpksk', 'pkdmzd', 'skdmzd']
  overwrite:
    value: false
  delta_weight:
    value: 0.0
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fullshot_3_dw0'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
# total runs: 3 combos
