program: train_clip_decoder.py
project: aaai27_encoder_mgpcgrl_fewshot
method: grid
metric:
  goal: minimize
  name: val/loss
parameters:
  game:
    value: 'all'
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fewshot_dw0'
  unseen_ratio:
    value: 0.03
  delta_weight:
    value: 0.0
  unseen_games:
    values:
      - 'pk'
      - 'dg'
      - 'zd'
      - 'dm'
      - 'sk'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}

