program: train_clip_decoder.py
project: aaai27_encoder_mgpcgrl_zeroshot
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  n_envs:
    value: 600
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_zeroshot_dw0'
  unseen_games:
    values:
      - 'dm'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
