program: train_clip_decoder.py
project: aaai27_encoder_mgpcgrl_fewshot
method: grid
metric:
  goal: minimize
  name: val/loss
parameters:
  game:
    value: 'all'
  seed:
    values: [0, 1, 2]
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fewshot_dwctrl'
  unseen_ratio:
    value: 0.03
  unseen_games:
    values:
      - 'pk'
      - 'dg'
      - 'zd'
      - 'dm'
      - 'sk'
  eval_unseen_ratio:
    value: 1.0
  delta_weight:
    values: [0.0]
  decoder_nograd:
    values: [false] # false
  unseen_eval_freq:
    value: 100
  export_unseen_predictions_csv:
    value: true
  compute_delta_when_zero:
    value: true
  ckpt_freq:
    value: 500
  ckpt_keep:
    value: 1000000
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
