program: train_reward.py
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0, 1, 2, 3, 4]
  n_envs:
    value: 500
  overwrite:
    value: false
  encoder.ckpt_dir:
    value: '/mnt/nas/mgpcgrl/reward_zeroshot_dw0'
  encoder.ckpt_name:
    values: [
      "clipdec-game-all_unseen-pk_ur-0.0_exp-def_dw-0p03_0",
      "clipdec-game-all_unseen-dg_ur-0.0_exp-def_dw-0p03_0",
      "clipdec-game-all_unseen-zd_ur-0.0_exp-def_dw-0p03_0",
      "clipdec-game-all_unseen-dm_ur-0.0_exp-def_dw-0p03_0",
      "clipdec-game-all_unseen-sk_ur-0.0_exp-def_dw-0p03_0",
    ]
  saves_dir:
    value: '/mnt/nas/mgpcgrl/reward_zeroshot_dw0'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
