program: train_mgpcgrl.py
project: aaai27_train_mgpcgrl_fewshot_seenrate
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    value: 'all'
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0, 1, 2, 3, 4]
  n_envs:
    value: 600
  overwrite:
    value: false
  train_seen_ratio:
    value: 1.0
  encoder.ckpt_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fewshot_seenrate'
  encoder.ckpt_name:
    values:
      - "clipdec-game-all_sr-0.0_unseen-zd_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.001_unseen-zd_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.003_unseen-zd_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.01_unseen-zd_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.03_unseen-zd_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.1_unseen-zd_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.0_unseen-zd_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.001_unseen-zd_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.003_unseen-zd_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.01_unseen-zd_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.03_unseen-zd_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.1_unseen-zd_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.0_unseen-dm_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.001_unseen-dm_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.003_unseen-dm_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.01_unseen-dm_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.03_unseen-dm_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.1_unseen-dm_ur-0.01_exp-def_0"
      - "clipdec-game-all_sr-0.0_unseen-dm_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.001_unseen-dm_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.003_unseen-dm_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.01_unseen-dm_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.03_unseen-dm_ur-0.03_exp-def_0"
      - "clipdec-game-all_sr-0.1_unseen-dm_ur-0.03_exp-def_0"
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_fewshot_seenrate'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
