program: train_ipcgrl.py
project: aaai27_train_ipcgrl_fullshot_3
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0, 1, 2, 3, 4]
  n_envs:
    value: 600
  overwrite:
    value: false
  encoder.ckpt_dir:
    value: '/mnt/nas/mgpcgrl/ipcgrl_fullshot_3'
  encoder.ckpt_name:
    values: [
      "ipcgrl-enc-mg-game-dgpksk_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-pkdmzd_enc-mlp_exp-def_0",
      "ipcgrl-enc-mg-game-skdmzd_enc-mlp_exp-def_0",
    ]
  saves_dir:
    value: '/mnt/nas/mgpcgrl/ipcgrl_fullshot_3'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
# total runs: 3 combos x 5 dataset_reward_enum x 5 seeds = 75
