program: train_clip_decoder.py
project: aaai27_encoder_mgpcgrl_fullshot_direction
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  delta_weight:
    values: [0.03, 0.05, 0.1]
  seed:
    values: [0]
  overwrite:
    value: false
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mgpcgrl_direction0623'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
