program: train_mipcgrl.py
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    values: ['all']
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0, 1, 2, 3, 4]
  n_envs:
    value: 600
  overwrite:
    value: false

  encoder.ckpt_dir:
    value: '/mnt/nas/mgpcgrl/mipcgrl_zeroshot'
  encoder.ckpt_name:
    values: [
      "mipcgrl-enc-mg-game-all_unseen-pk_ur-0.0_enc-mlp_exp-def_0",
      "mipcgrl-enc-mg-game-all_unseen-dg_ur-0.0_enc-mlp_exp-def_0",
      "mipcgrl-enc-mg-game-all_unseen-zd_ur-0.0_enc-mlp_exp-def_0",
      "mipcgrl-enc-mg-game-all_unseen-dm_ur-0.0_enc-mlp_exp-def_0",
      "mipcgrl-enc-mg-game-all_unseen-sk_ur-0.0_enc-mlp_exp-def_0",
    ]
  saves_dir:
    value: '/mnt/nas/mgpcgrl/mipcgrl_zeroshot'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
