program: train_mgpcgrl.py
project: aaai27_train_mgpcgrl_fewshot
method: grid
metric:
  goal: minimize
  name: unseen/reg_unseen_overall
parameters:
  game:
    value: 'all'
  dataset_reward_enum:
    values: [0, 1, 2, 3, 4]
  seed:
    values: [0]
  n_envs:
    value: 600
  overwrite:
    value: false
  train_seen_ratio:
    value: 1.0
  dataset_unseen_ratio:
    value: 0.3
  encoder.ckpt_dir:
    value: '/mnt/nas/mgpcgrl/predictive_reward'
  encoder.ckpt_name:
    values:
      - "clipdec-game-all_unseen-dm_ur-0.03_exp-def_0"
      - "clipdec-game-all_unseen-dm_ur-0.03_exp-def_dw-0p03_0"
  saves_dir:
    value: '/mnt/nas/mgpcgrl/predictive_reward'
command:
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}

